### ISSUE TITLE
react-scripts start fails on system: Ubuntu 16.04

### ISSUE THREAD

**Issue by sendqwertr** [snowypowers/ansy#1]
When running "npm install":
```
npm WARN optional Skipping failed optional dependency /react-scripts/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN eslint-config-react-app@2.0.0 requires a peer of eslint@^4.1.1 but none was installed.
npm WARN ansy@2.0.0 No repository field.
npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ansy/npm-debug.log
```
npm-debug.log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ansy@2.0.0~prestart: ansy@2.0.0
6 silly lifecycle ansy@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle ansy@2.0.0~start: ansy@2.0.0
8 verbose lifecycle ansy@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ansy@2.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/root/ansy/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle ansy@2.0.0~start: CWD: /root/ansy
11 silly lifecycle ansy@2.0.0~start: Args: [ '-c', 'react-scripts start' ]
12 info lifecycle ansy@2.0.0~start: Failed to exec start script
13 verbose stack Error: ansy@2.0.0 start: `react-scripts start`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid ansy@2.0.0
15 verbose cwd /root/ansy
16 error Linux 4.4.0-87-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error ansy@2.0.0 start: `react-scripts start`
24 error spawn ENOENT
25 error Failed at the ansy@2.0.0 start script 'react-scripts start'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the ansy package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     react-scripts start
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs ansy
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls ansy
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by snowypowers** [comment]
Not sure about this, you should try to update your node version.
